version: '2'
services:
  web:
    image: nginx:latest
    ports:
      - "8080:80"
    volumes:
      - ./index.html:/usr/share/nginx/html/index.html
      - ./elm.js:/usr/share/nginx/html/elm.js
      - ./style.css:/usr/share/nginx/html/style.css
    links:
      - postgrest

  postgrest:
    image: motiz88/postgrest:latest
    ports:
      - "3333:3000"
    links:
      - postgres:postgres
    environment:
      DBHOST: postgres
      DBNAME: routinely
      DBUSER: routinely
      DBPASS: password
      ANONUSER: routinely

  postgres:
    image: postgres
    ports:
      - 5432
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./api/schema.sql:/docker-entrypoint-initdb.d/schema.sql
      - ./api/seed.sql:/docker-entrypoint-initdb.d/seed.sql
    environment:
      POSTGRES_DB: routinely
      POSTGRES_USER: routinely
      POSTGRES_PASSWORD: password

volumes:
  postgres-data: {}
